language: node_js
notifications:
  email: false
node_js:
  - 'node'
script: npm start validate
after_success:
  - npm install -g codecov semantic-release
  - codecov
  - semantic-release pre && npm publish && semantic-release post
branches:
  except: /^v\d+\.\d+\.\d+$/
